### ISSUE TITLE
Don't know how to process TCP option 34

### ISSUE THREAD

**Issue by yannbertrand** [pownjs/pown#2]
Hi,

I have this issue running `sudo pown now -a httpview rvi0`
<img width="631" alt="screenshot 2018-11-08 at 10 08 38" src="https://user-images.githubusercontent.com/5855339/48188573-5e0a2200-e33e-11e8-8b04-7b95d8870e7e.png">

Furthermore, Safari opens https://httpview.secapps.com but gives a blank page with errors in my console:
<img width="731" alt="screenshot 2018-11-08 at 10 11 08" src="https://user-images.githubusercontent.com/5855339/48188690-a45f8100-e33e-11e8-81b4-0dfc99afb560.png">

Do you know what is happening? I'm not sure these issues are related.

Thanks by advance

macOS 10.14
node 8.12.0
pown 1.6.0

**Comment by pdparchitect** [comment]
HTTPView does not currently work on Safari. Only Chrome and Firefox are supported. The error in pown now is standard unfortunately but we will be looking at workarounds.

**Comment by pdparchitect** [comment]
I am closing this issue because it is now not relevant to Pown2. Thanks or the report.
