### ISSUE TITLE
cannot create generated/aesprim-browser.js

### ISSUE THREAD

**Issue by new-gen23** [pownjs/pown#5]
I tried to install it in kali linux and get the error:
npm install -g pown@latest
`/usr/local/bin/pown -> /usr/local/lib/node_modules/pown/bin/pown.js

> jsonpath@1.0.2 postinstall /usr/local/lib/node_modules/pown/node_modules/jsonpath
> node lib/aesprim.js > generated/aesprim-browser.js

sh: 1: cannot create generated/aesprim-browser.js: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! jsonpath@1.0.2 postinstall: `node lib/aesprim.js > generated/aesprim-browser.js`
npm ERR! Exit status 2`

I have no clue to which path the error is referring... any ideas?

**Comment by michaelkruglos** [comment]
This problem is caused by dchester/jsonpath#122
The workaround in the mean time is described in https://github.com/dchester/jsonpath/issues/122#issuecomment-537284400
But it's bad. They should fix it.

**Comment by new-gen23** [comment]
heh, almost a year since I tried your tool. Funny.  Anyway, I installed using npm without error. Closing the issue.
